language: node_js
node_js: stable
before_install:
- openssl aes-256-cbc -K $encrypted_8fb06a7aa9ef_key -iv $encrypted_8fb06a7aa9ef_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
addons:
script:
- npm install
- npm run build
after_success:
- scp -o stricthostkeychecking=no -r dist root@$DEPLOY_HOST:/home/www/homepage/
